---
- name: Ensure prerequisite packages are present (Debian)
  apt:
    name: "{{ vector_packages_debian }}"
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure prerequisite packages are present (RedHat)
  yum:
    name: "{{ vector_packages_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Download Vector package (Debian)
  get_url:
    url: "{{ vector_download_deb }}"
    dest: "/tmp/vector_{{ vector_version }}.deb"
    mode: "0644"
  when: vector_pkg_type == "deb"

- name: Install Vector (Debian)
  apt:
    deb: "/tmp/vector_{{ vector_version }}.deb"
    state: present
  when: vector_pkg_type == "deb"

- name: Download Vector package (RPM)
  get_url:
    url: "{{ vector_download_rpm }}"
    dest: "/tmp/vector-{{ vector_version }}.rpm"
    mode: "0644"
  when: vector_pkg_type == "rpm"

- name: Install Vector (RPM)
  yum:
    name: "/tmp/vector-{{ vector_version }}.rpm"
    state: present
  when: vector_pkg_type == "rpm"

- name: Ensure config dir exists
  file:
    path: "{{ vector_config_path | dirname }}"
    state: directory
    mode: "0755"

- name: Deploy Vector config
  template:
    src: "vector.toml.j2"
    dest: "{{ vector_config_path }}"
    mode: "0644"
  notify: Restart vector

- name: Enable and start Vector
  service:
    name: "{{ vector_service_name }}"
    state: started
    enabled: yes
